// Code generated by Slice Machine. DO NOT EDIT.

import Donut from './Donut/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	donut: Donut,
	hero: Hero,
	rich_text: RichText
};
